version: '3'

services:
  peatio:
    build:
      context: peatio
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
      - peatio_daemons
      - barong
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - URL_HOST=peatio:8000
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme
      - RABBITMQ_HOST=rabbitmq
      - SMTP_PORT=25
      - SMTP_DOMAIN=helioscloud.com
      - SMTP_ADDRESS=smtp-relay
      - SMTP_USE_SSL=false
      - SMTP_USE_TLS=false
      - SMTP_ENABLE_STARTTLS=false
      - SMTP_ENABLE_STARTTLS_AUTO=false
      - OAUTH2_SIGN_IN_PROVIDER=barong
      - BARONG_DOMAIN=http://barong:8001
      - BARONG_OAUTH2_REDIRECT_URL=http://localhost:4200/callback
      - BARONG_CLIENT_ID=087c8803986a809a60b267c268a1ffc90d3c4b0cb2b83728f5b78c208710bdbd
      - BARONG_CLIENT_SECRET=70f57eacc91fe639466888ed0c4948ce1d5000e0c6ea68691a943b47389276a2
    volumes:
      - ./peatio:/home/app

  peatio_daemons:
    build:
      context: peatio
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
      - coinhub
    ports:
      - "8080:8080"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./peatio:/home/app
    command: god -c lib/daemons/daemons.god -D start

  peatio_specs:
    build:
      context: peatio
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - PORT=8000
      - RAILS_ENV=test
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme
      - RABBITMQ_HOST=rabbitmq
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=peatio
      - TEST_APP_PORT=8080
    volumes:
      - ./peatio:/home/app
    entrypoint:
      - /bin/sh
      - -exc
    command:
      - |
        bundle exec rspec --exclude-pattern=spec/features/**/*_spec.rb

  barong:
    build:
      context: barong
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=changeme
    volumes:
      - ./barong:/home/app

  coinhub:
    image: rubykube/coinhub

  smtp-relay:
    image: kaigara/postfix:latest
    volumes:
      - ./smtp-relay.yaml:/etc/kaigara/metadata/relay.yml

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: peatio_development
      MYSQL_USER: peatio
      MYSQL_PASSWORD: changeme

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:alpine

  selenium:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600

volumes:
  db_data:
