- id:                   1
  code:                 usd
  symbol:               '$'
  type:                 fiat
  precision:            2
  base_factor:          1
  visible:              true
  quick_withdraw_limit: 1000

- id:                   2
  code:                 btc
  symbol:               'Ƀ'
  type:                 coin
  precision:            8
  base_factor:          100_000_000
  visible:              true
  quick_withdraw_limit: 0.1
  options:
    #
    # API client configuration.
    api_client: BTC
    #
    # Bitcoind specific configuration.
    json_rpc_endpoint: http://user:password@127.0.0.1:18332
    #
    # BitGo specific configuration.
    bitgo_test_net:              on
    bitgo_wallet_id:             ~
    bitgo_wallet_address:        ~
    bitgo_wallet_passphrase:     ~
    bitgo_rest_api_root:         https://test.bitgo.com/api/v2
    bitgo_rest_api_access_token: ~
    #
    # Block explorer configuration.
    wallet_url_template:      https://live.blockcypher.com/btc-testnet/address/#{address}
    transaction_url_template: https://live.blockcypher.com/btc-testnet/tx/#{txid}

- id:                   3
  code:                 bch
  symbol:               '฿'
  type:                 coin
  precision:            8
  base_factor:          100_000_000
  visible:              true
  quick_withdraw_limit: 1
  options:
    #
    # API client configuration.
    api_client: BCH
    #
    # Bitcoin Cash daemon specific configuration.
    json_rpc_endpoint: http://user:password@127.0.0.1:18332
    #
    # BitGo specific configuration.
    bitgo_test_net:              on
    bitgo_wallet_id:             ~
    bitgo_wallet_address:        ~
    bitgo_wallet_passphrase:     ~
    bitgo_rest_api_root:         https://test.bitgo.com/api/v2
    bitgo_rest_api_access_token: ~
    #
    # Block explorer configuration.
    wallet_url_template:      https://www.blocktrail.com/tBCC/address/#{address}
    transaction_url_template: https://www.blocktrail.com/tBCC/tx/#{txid}

