- id: 1
  uid: ID53B3505544
  currency: btc
  amount:   100
  state:    accepted
- id: 2
  uid: ID53B3505544
  currency: xrp
  amount:   100
  state:    accepted
- id: 3
  uid: ID53B3505544
  currency: usd
  amount:   10
  state:    accepted