- id:     multi
  orders:
    - id:     1
      side:   sell
      volume: 0.002
      price:  20
    - id:     2
      side:   sell
      volume: 0.001
      price:  20.5
    - id:     3
      side:   sell
      volume: 0.001
      price:  19
    - id:     4
      side:   buy
      volume: 0.001
      price:  18.3
    - id:     5
      side:   buy
      volume: 0.001
      price:  18.4
    - id:     6
      side:   buy
      volume: 0.001
      price:  18.35
- id:     buy
  order: 
    side:   buy
    volume: 0.002
    price:  20.5
- id:     sell
  order:
    side:   sell
    volume: 0.002
    price:  18.34