# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workbench
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Install ruby dependencies
          command: "bundle install"
      - run:
          name: Add hosts
          command: |
            echo 0.0.0.0 www.wb.local | sudo tee -a /etc/hosts && \
            echo 0.0.0.0 peatio.wb.local | sudo tee -a /etc/hosts && \
            echo 0.0.0.0 barong.wb.local | sudo tee -a /etc/hosts && \
            echo 0.0.0.0 ws.ranger.wb.local | sudo tee -a /etc/hosts
      - run:
          name: Download apps
          command: "make update"
      - run:
          name: Build docker images
          command: "make build"
      - run:
          name: Run workbench
          command: "make start"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
