version: '3.6'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
      - barong
      - ranger
      - geth
      - coinhub
    env_file:
      - ../config/peatio.env
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
      - ../app/peatio/app:/home/app/app
      - ../app/peatio/lib:/home/app/lib
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: wb.local; PathPrefix:/peatio'
      traefsik.port:
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  barong:
    build:
      context: ../app/barong
    depends_on:
      - proxy
      - db
      - vault
      - mailcatcher
    env_file:
      - ../config/barong.env
    volumes:
      - ../config/barong:/opt/barong/config:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: wb.local; PathPrefix:/auth'
      traefik.port: 8001

  trading_ui:
    build:
      context: ../app/trading-ui
    depends_on:
      - proxy
      - peatio
    env_file:
      - ../config/trading-ui.env
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: wb.local; PathPrefix:/trade, /trade-ui-assets'
      traefik.port: 8002
