version: '3.6'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
      - barong
      - ranger
      - geth
      - coinhub
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - peatio-assets:/home/app/app/assets
      - ../config/peatio:/opt/peatio/config:ro
      - ../app/peatio/app:/home/app/app
      - ../app/peatio/lib:/home/app/lib
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  barong:
    build:
      context: ../app/barong
    depends_on:
      - proxy
      - db
      - vault
      - mailcatcher
    env_file:
      - ../config/barong.env
    volumes:
      - barong-assets:/home/app/app/assets
      - ../config/barong:/opt/barong/config:ro
      - ../app/barong/app:/home/app/app
      - ../app/barong/lib:/home/app/lib
    expose:
      - "8001"

  trading_ui:
    build:
      context: ../app/trading-ui
    depends_on:
      - proxy
      - peatio
    env_file:
      - ../config/trading-ui.env
    expose:
      - "8002"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.wb.local; PathPrefix:/peatio/trading, /peatio/trading-ui-assets'
      traefik.port: 8002

  barong_assets:
    image: nginx
    depends_on:
      - barong
      - proxy
    volumes:
      - barong-assets:/var/www/app:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.wb.local; PathPrefixStrip:/barong/assets'
      traefik.port: 80

  peatio_assets:
    image: nginx
    depends_on:
      - peatio
      - proxy
    volumes:
      - peatio-assets:/var/www/app:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.wb.local; PathPrefixStrip:/peatio/assets'
      traefik.port: 80

volumes:
  peatio-assets:
  barong-assets: