version: '3'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
      - smtp_relay
      - peatio_daemons
      - barong
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: api.wb.local'
      traefik.port: 8000

  peatio_daemons:
    build:
      context: ../app/peatio
    depends_on:
      - db
      - redis
      - rabbitmq
      - coinhub
    env_file:
      - ../config/peatio.env
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
    command: god -c lib/daemons/daemons.god -D start

  barong:
    build:
      context: ../app/barong
    depends_on:
      - proxy
      - db
      - vault
    env_file:
      - ../config/barong.env
    expose:
      - "8001"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: auth.wb.local'
      traefik.port: 8001
