version: '3.2'

services:

  peatio:
    build:
      context: ../app/peatio
    container_name: peatio
    depends_on:
      - db
      - redis
      - rabbitmq
      - smtp_relay
      - peatio_daemons
      - barong
    ports:
      - "8000:8000"
    env_file:
      - ../config/peatio/application.env
    environment:
      DATABASE_USER: root
      DATABASE_PASS: changeme
    volumes:
      - ../config/peatio:/opt/peatio/config:ro

  peatio_daemons:
    build:
      context: ../app/peatio
    container_name: peatio-daemons
    depends_on:
      - db
      - redis
      - rabbitmq
      - coinhub
    ports:
      - "8080:8080"
    env_file:
      - ../config/peatio/application.env
    environment:
      DATABASE_USER: root
      DATABASE_PASS: changeme
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
    command: god -c lib/daemons/daemons.god -D start

  barong:
    build:
      context: ../app/barong
    container_name: barong
    depends_on:
      - db
      - vault
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: changeme
      VAULT_TOKEN: changeme
      VAULT_ADDR: http://vault:8200

