version: '3.7'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
      - barong
      - ranger
      - coinhub
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api_v1.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
      - ../app/peatio/app:/home/app/app
      - ../app/peatio/lib:/home/app/lib
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  barong:
    build:
      context: ../app/barong
    depends_on:
      - proxy
      - db
      - vault
      - mailcatcher
    env_file:
      - ../config/barong.env
    volumes:
      - ../config/barong:/opt/barong/config:ro
      - ../config/keys/barong.key:/secrets/barong.key
    expose:
      - "8001"
