version: '3.6'

services:
  geth:
    image: ethereum/client-go:stable
    command: |
      --syncmode=full
      --rinkeby
      --rpc
      --rpcaddr=0.0.0.0
      --rpcport=8545
      --port=30303
      --rpcapi="db,personal,eth,net,web3"
      --rpccorsdomain="*"
      --rpcvhosts="*"
    volumes:
      - eth-data:/root/.ethereum/
    expose:
      - "8545"
      - "30303"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: eth.wb.local'
      traefik.port: 8545

  bitcoind:
    image: kylemanna/bitcoind
    command: |
      -testnet
      -printtoconsole
      -server
      -port=8332
      -rpcport=8333
      -rpcallowip=0.0.0.0/0
      -rpcuser=admin
      -rpcpassword=changeme
    volumes:
      - btc-data:/bitcoin
    expose:
      - "8332"
      - "8333"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: btc.wb.local'
      traefik.port: 8332

volumes:
  eth-data:
  btc-data:
