version: '3.6'

services:
  geth:
    image: ethereum/client-go:stable
    command: |
      --syncmode light --rinkeby --rpc --rpcport="8545" --rpcapi="db,personal,eth,net,web3"
      --rpcaddr="0.0.0.0" --rpccorsdomain="*" --rpcvhosts="*" --port="30303"
    volumes:
      - eth-data:/root/.ethereum/
    expose:
      - "8545"
      - "30303"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: eth.wb.local'
      traefik.port: 8545

volumes:
  eth-data:
