version: '3.7'

services:
  gateway:
    image: quay.io/datawire/ambassador:0.40.2
    volumes:
      - ../config/gateway:/ambassador/ambassador-config
    ports:
      - '8081:80'
      - '8877:8877'
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: www.wb.local; PathPrefix: /api/, /admin, /assets/"
      traefik.port: 80
