version: '3'

services:
  proxy:
    image: traefik:1.6
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - api.wb.local
          - auth.wb.local
