version: '3.6'

services:
  integration:
    build:
      context: ../app/integration
    volumes:
      - ../config/integration/fixtures:/usr/src/app/fixtures/

  toolbox:
    build:
      context: ../app/toolbox
    entrypoint: bin/stress_trading

  selenium:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
