version: '3'

services:

  toolbox:
    build:
      context: ../toolbox
    entrypoint: bin/stress_trading

  selenium:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
