version: '3'

services:
  jest:
    build:
      context: ../test-jest
    depends_on:
      - peatio
      - barong
    env_file:
      - ../.env
      - ../config/jest.env

  selenium:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
