version: '3.6'

services:

  toolbox:
    build:
      context: ../app/toolbox
    entrypoint: bin/stress_trading

  selenium:
    image: selenium/standalone-chrome
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600
