# List of Barong administrators.
#
# Other parameters that you can set here can be found in Account,
# Profile and Phone models (e.g. app/models/account.rb...); all the
# model properties are listed at the very bottom of this models files.
#
# Note: email is the only required field here.

accounts:
  - account:
      email: admin@barong.io
      password: "Qwerty123"
      role: admin
      state: active
      level: 3
  - account:
      email: PhillipaRuais@gmail.com
      password: "x796f7b98ufkjx2W"
      role: admin
      state: active
      level: 3
    phone:
      country: "FR"
      number: "33755882002"
    profile:
      first_name: "Phillipa"
      last_name: "Ruais"
      address: "62 boulevard d'Alsace"
      postcode: "78140"
      city: "VÉLIZY-VILLACOUBLAY"
      country: "FR"
  - account:
      email: AntoinePelletier@gmail.com
      password: "x796f7b98ufkjx2W"
      role: member
      state: active
      level: 0
    phone:
      country: "FR"
      number: "33755882189"
    profile:
      first_name: "Antoine"
      last_name: "Pelletier"
      address: "94 rue Charles Corbeau"
      postcode: "76400"
      city: "FÉCAMP"
      country: "FR"
  - account:
      email: CecileVaillancourt@gmail.com
      password: "x796f7b98ufkjx2W"
      role: member
      state: active
      level: 1
    phone:
      country: "FR"
      number: "40729371571"
    profile:
      first_name: "Cécile"
      last_name: "Vaillancourt"
      address: "45 rue Saint Germain"
      postcode: "92230"
      city: "GENNEVILLIERS"
      country: "FR"
  - account:
      email: CharmaineOuellet@gmail.com
      password: "x796f7b98ufkjx2W"
      role: member
      state: active
      level: 2
    phone:
      country: "FR"
      number: "447383453439"
    profile:
      first_name: "Charmaine"
      last_name: "Ouellet"
      address: "22 rue du Président Roosevelt"
      postcode: "49400"
      city: "SAUMUR"
      country: "FR"
  - account:
      email: RamonLMcCourt@gmail.com
      password: "x796f7b98ufkjx2W"
      role: member
      state: active
      level: 3
    phone:
      country: "US"
      number: "17542058966"
    profile:
      first_name: "Ramon"
      last_name: "McCourt"
      address: "224 Spirit Drive"
      postcode: "32008"
      city: "Branford"
      country: "US"
  - account:
      email: AmyJBriggs@gmail.com
      password: "x796f7b98ufkjx2W"
      role: member
      state: active
      level: 3
    phone:
      country: "US"
      number: "17722002528"
    profile:
      first_name: "Amy"
      last_name: "Briggs"
      address: "3848 Mount Tabor"
      postcode: "10601"
      city: "White Plains"
      country: "US"
  - account:
      email: DavidTMoore@gmail.com
      password: "x796f7b98ufkjx2W"
      role: member
      state: active
      level: 3
    phone:
      country: "US"
      number: "19706823057"
    profile:
      first_name: "David"
      last_name: "Moore"
      address: "41 Aviation Way"
      postcode: "90071"
      city: "Los Angeles"
      country: "US"

# List of applications that will use Barong OAuth.
# You can set any Doorkeeper::Application property here.
#
# Note: in production env, `redirect_uri` can only be a 'https' url.
applications:
  - name: "Peatio"
    redirect_uri: "http://api.wb.local/auth/barong/callback"
    skipauth: true
    uid: "a68be319fca51caca60eed5711226e568bd1c1d13ff452b945515f1a6ffbaca4"
    secret: "ab80e2c843861c4d23e63f5472cd1c9ee6f55e388863e21f22b03a9093977f29"

levels:
  - key: email
    value: verified
    description: "User clicked on the confirmation link"
  - key: phone
    value: verified
    description: "User entered a valid code from sms"
  - key: document
    value: verified
    description: "User personal documents have been verified"
