- id:            usdeth
  ask_unit:      usd
  bid_unit:      eth
  ask_fee:       0.0015
  bid_fee:       0.0015
  ask_precision: 8
  bid_precision: 8
  position:      100
  enabled:       true

- id:            usdbtc
  ask_unit:      usd
  bid_unit:      btc
  ask_fee:       0.0015
  bid_fee:       0.0015
  ask_precision: 8
  bid_precision: 8
  position:      100
  enabled:       true
